#######################
# Spring boot properties
# http://docs.spring.io/spring-boot/docs/current/reference/html/common-application-properties.html
########################

spring:
  mvc:
    view:
      prefix: /WEB-INF/jsp/
      suffix: .jsp
      
  output:
    ansi:
      enabled: ALWAYS

  datasource:
    url: jdbc:derby:memory:animal;create=true
    driver-class-name: org.apache.derby.jdbc.EmbeddedDriver
    hikari:
      connection-test-query: SELECT 1
      maximum-pool-size: 50
      minimum-idle: 20

  jpa:
    open-in-view: false
    properties:
      hibernate:
        ddl-auto: create-drop
        dialect: org.hibernate.dialect.DerbyDialect
    show-sql: false
